blockchain/wallet-options

- __tests__/index.spec.js
- scripts/json-format.js
- testnet/wallet-options.json
Missed this this one in the original PR.
> Validate testnet options file with schema

- testnet/wallet-options.json
No rush, just didn't want to forget this.
> SFOX testnet key

- prod/wallet-options.json
Update service alert banner text in response to user confusion.
> Update service alert copy

- prod/wallet-options.json
Please deploy to production at your earliest convenience. Thanks
@tuzzolo if Mark is in transit today could you deploy this by any chance? Better to get new orders in earlier in the week if possible.
> feat(SFOX): IL, MA, VA release

- dev/wallet-options.json
- prod/wallet-options.json
- src/schema.js
- staging/wallet-options.json
- testnet/wallet-options.json
Adds lastTxFuse time in seconds for testing/production. 10 minutes on staging 1 day on production. Can just be merged to testing envs for now. Thanks
> Add lastTxFuse

- dev/wallet-options.json
- prod/wallet-options.json
- src/schema.js
- staging/wallet-options.json
- testnet/wallet-options.json
> feat(Buy): show buy fraction

- dev/wallet-options.json
- prod/wallet-options.json
- src/schema.js
- staging/wallet-options.json
- testnet/wallet-options.json
Flag is unused in current App Store version.
> feat(iOS Sfox): Add flag for showing Sfox for iOS

- staging/wallet-options.json
@jamaayy requesting that we hide buy/sell on staging to make sure no announcements show for sfox
> feat(BuySell): hide on stging sfox

- staging/wallet-options.json
@jamaayy requesting showing sfox on mobile
> feat(SFOX): show on mobile stg

- prod/wallet-options.json
Please don't merge until we get the green light.
> bump sfox rollout to 5%

- staging/wallet-options-v4.json
@matsjj are you able to deploy?
> Set up v4 staging options

- dev/wallet-options-v4.json
Corrects the partnerId for Coinify on dev ENV
> options for coinify

- prod/wallet-options.json
> fix(Alert): use dismiss option

- dev/wallet-options.json
- prod/wallet-options.json
- src/schema.js
- staging/wallet-options.json
- testnet/wallet-options.json
Non-production urls intentionally left `null`. @tuzzolo
> Add comRoot and comWalletApp to domains

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
Copied over from staging v4 options, with changes to domains and buy/sell
> prod wallet options for v4

- .gitignore
- dev/wallet-options-v4.json
- staging/wallet-options-v4.json
Adds a few different announcements to v4 wallet options for dev and staging.
Will eventually need to update or add a new v4 schema for prod support.
> V4 service announcements support

- prod/wallet-options.json
PR for the wallet-options that must be live when .com wallet goes into production.
> .info -> .com production

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
> Fix ss-max across envs

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
> feat(v4): launch

- dev/wallet-options-v4.json
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Can wait until https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/967 and https://github.com/blockchain/service-wallet-helper/pull/23 are merged
> plaid dev/staging env --> sandbox

- prod/wallet-options-v4.json
> fix(Prod v4): remove announcement

- prod/wallet-options-v4.json
- prod/wallet-options.json
v4 and .com announcement banners
> Announcement banner

- prod/wallet-options-v4.json
- prod/wallet-options.json
- staging/wallet-options-v4.json
These are already present in Resources, but just to commit them to master
> Add ledger urls to wallet-options

- dev/wallet-options-v4.json
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
- disables BCH send, receive and exchange in staging
- updates messaging
> Simulate fork in staging 

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
- Disables BCH send, receive and exchange
- Adds announcements in english only (still waiting on translations)
> Wallet: Update service messaging and disable BCH

- staging/wallet-options.json
Mimic change from web here:
https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/1182/files#diff-8652b7353685b786a141aab3f840926fR29
Once confirmed working, will PR to prod.
> feat(BCH): bump fees for additional dust

- dev/wallet-options.json
- prod/wallet-options.json
> Update bch fee per byte to 4 for BCH on dev and prod.

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Merge whenever no rush, already deployed to staging
> Update bch messaging and add lockbox flag

- testnet/wallet-options-v4.json
> v4(Testnet actual fix)

- staging/wallet-options.json
Testing this on staging first. Will PR to production next.
> Add notice to upgrade to 2.8.3 to access Swap (staging).

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- src/types.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
This is for migrating to new the new "coin model" v4 wallet options schema.  This has both the old and new the models for coins.  Another PR will follow tomorrow with the old models removed.
> v4 wallet options schema

- staging/wallet-options.json
Need to add US in coinify country list for testing (only on staging)
> Add US to Coinify countries for testing.

- staging/wallet-options.json
Turning off SFOX on staging to mimic what's in prod
> Turn off SFOX on staging.

- prod/wallet-options-v4.json
Reverts blockchain/wallet-options#157
> Revert "Add bch fork annc"

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
- Adds support to display service announcements to Swap and Lockbox pages.  
- V4 PR w/ screenshots => https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/1632
> V4(Swap/Lockbox service announcements)

- package.json
- testnet/wallet-options-v4.json
- yarn.lock
- Adds `Husky` which will run the repo's tests when dev pushes branch to origin
- Updates dependencies
> Feat(Add commit hook)

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Can be deployed whenever to all envs according to Franklin
> Change USD Pax to USD PAX

- dev/wallet-options.json
- prod/wallet-options.json
- src/schema.js
- staging/wallet-options.json
- testnet/wallet-options.json
* Android messaging for XLM service interruption.
* Move Horizon URL to wallet-options
> Android messaging for XLM service interruption.

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Can we deploy on all envs pls?
> Add ads blacklist

- src/types.js
- testnet/wallet-options-v4.json
> fix(Testnet): use correct btc network per test env

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
> Add sift apiKey to WO envs

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
> Fix(Disable BSV send)

- prod/wallet-options-v4.json
@mpfluger can deploy to prod when ready
> Fix prod beta link for pit

- prod/wallet-options.json
> Android recommend upgrade production.

- dev/wallet-options-v4.json
- staging/wallet-options-v4.json
- Dev and staging for now, will do prod when ready for release
> Remove Lockbox service announcement

- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
Please merge and deploy this before next web wallet release
- Removes lockbox announcement
- Allows PIT banners to users in Canada and Netherlands
> Prod Release(Remove lockbox announcement, add PIT marketing countries)

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
Added learn more links for bch, eth, usd-d.
> fix(coins): learn more links

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Already pushed to staging, can go to every env
> feat(simple buy): add everypay urls

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Deployed to dev/staging. Please do **not** deploy to prod
> feat(usdt/algo): add coins

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/schema.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
Please merge and deploy to all envs at your earliest convenience
> feat(sift p): paymentKey added

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
@mpfluger please merge and deploy to prod at earliest convenience
> fix(usd): fix usd display name

- staging/wallet-options-v4.json
I've deployed this change the staging, no change necessary for prod
> Small update for design

- dev/wallet-options-v4.json
- prod/wallet-options-v4.json
- src/types.js
- staging/wallet-options-v4.json
- testnet/wallet-options-v4.json
@mpfluger merge and deploy to all envs
> fix(wallet linking): use syncToPit instead of syncToExchange

- dev/wallet-options.json
- staging/wallet-options.json
[Dev, Staging] Add maintenance message for iOS users.
> wallet options v3 downtime message [Dev, Staging]

- prod/wallet-options.json
[PROD] Add maintenance message for iOS users.
> wallet options v3 downtime message Prod

- dev/wallet-options.json
- staging/wallet-options.json
Using correct key for `mobileInfo `
> wallet options v3 downtime message [Staging, Dev]

- prod/wallet-options.json
Using correct key for `mobileInfo `
> wallet options v3 downtime message [Prod]

- prod/wallet-options.json
Disable the maintenance flag for iOS clients.
> chore(disable maintenance mode): Disable maintenance mode in prod

- dev/wallet-options.json
- prod/wallet-options.json
- staging/wallet-options.json
This reverts commit a563fa343e312aafb0caea51f7a11c7b864ee411.
> Revert "feat(stellar): Use blockdaemon nodes"

- dev/wallet-options.json
- prod/wallet-options.json
- staging/wallet-options.json
https://blockc.slack.com/archives/C01TG3HG546/p1635236368052400
https://github.com/blockchain/wallet-options/pull/262 (Original PR)
https://github.com/blockchain/wallet-options/pull/263 (Revert #262)
> feat(stellar): Use blockdaemon nodes

- dev/wallet-options.json
- staging/wallet-options.json
Add the same `hotWalletAddresses` structure from [V4](https://github.com/blockchain/applications/commit/855e62317b32bdffa21a1eadd5bacbb0a87426c1#diff-f0789f9440968e7ce694396fed665619f79b7de893392ae1243b51a2b8e4d5a3) to `staging` and `dev`.
> Add hotWalletAddresses to wallet options v3

- src/schema.js
Add hotWalletAddresses to schema, tests pass.
> Add hotWalletAddresses to schema
